//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment6.WordCountRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordCountRef.IWordCountService")]
    public interface IWordCountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCountService/CountWords", ReplyAction="http://tempuri.org/IWordCountService/CountWordsResponse")]
        int CountWords(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCountService/CountWords", ReplyAction="http://tempuri.org/IWordCountService/CountWordsResponse")]
        System.Threading.Tasks.Task<int> CountWordsAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordCountServiceChannel : Assignment6.WordCountRef.IWordCountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordCountServiceClient : System.ServiceModel.ClientBase<Assignment6.WordCountRef.IWordCountService>, Assignment6.WordCountRef.IWordCountService {
        
        public WordCountServiceClient() {
        }
        
        public WordCountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordCountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountWords(string text) {
            return base.Channel.CountWords(text);
        }
        
        public System.Threading.Tasks.Task<int> CountWordsAsync(string text) {
            return base.Channel.CountWordsAsync(text);
        }
    }
}
